
from __future__ import annotations

import io
from datetime import datetime

import pandas as pd
import streamlit as st
from sqlalchemy import MetaData, Table, inspect, select

from synthetic.generator import SURVEY_TEMPLATES, generate_synthetic_survey
from database.manager import create_engine_from_url


def _active_external():
    url = st.session_state.get("db_manager_url", "")
    platform = st.session_state.get("db_manager_platform", "")
    label = st.session_state.get("db_manager_label", "")
    schema = st.session_state.get("db_manager_schema", "") or ("dbo" if platform == "Microsoft SQL Server" else "public" if platform == "PostgreSQL" else "")
    return url, platform, label, schema


def _excel_bytes(df: pd.DataFrame) -> bytes:
    out = io.BytesIO()
    with pd.ExcelWriter(out, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Synthetic_Data")
    return out.getvalue()


def save_synthetic_to_external_db(df: pd.DataFrame, project_key: str, project_name: str, schema: str | None) -> tuple[bool, str]:
    url, platform, _, active_schema = _active_external()
    if not url:
        return False, "No external database connection is active. Connect to a database in Database Manager first."
    schema = schema or active_schema or None
    engine = create_engine_from_url(url)
    try:
        insp = inspect(engine)
        required = {"gp_projects", "gp_datasets", "gp_stations", "gp_magnetic_observations", "gp_gravity_observations"}
        existing = set(insp.get_table_names(schema=schema))
        missing = required - existing
        if missing:
            return False, "External Geophysics schema is not initialized. Missing: " + ", ".join(sorted(missing))

        meta = MetaData()
        projects = Table("gp_projects", meta, autoload_with=engine, schema=schema)
        datasets = Table("gp_datasets", meta, autoload_with=engine, schema=schema)
        stations = Table("gp_stations", meta, autoload_with=engine, schema=schema)
        magnetic = Table("gp_magnetic_observations", meta, autoload_with=engine, schema=schema)
        gravity = Table("gp_gravity_observations", meta, autoload_with=engine, schema=schema)

        with engine.begin() as conn:
            proj = conn.execute(select(projects).where(projects.c.project_key == project_key)).first()
            if proj is None:
                conn.execute(projects.insert().values(project_key=project_key, name=project_name, country="Synthetic", region="Synthetic Test Area", crs_epsg=4326, description="Synthetic demonstration project."))

            dataset_type = "COMBINED" if {c for c in df.columns if c.startswith("Mag_")} and {c for c in df.columns if c.startswith("Gravity_")} else ("MAGNETIC" if any(c.startswith("Mag_") for c in df.columns) else "GRAVITY")
            result = conn.execute(datasets.insert().values(project_key=project_key, name=f"Synthetic {dataset_type} {datetime.now():%Y%m%d_%H%M%S}", dataset_type=dataset_type, survey_type=str(df["Survey_Template"].iloc[0]), units="nT / mGal", source_description="Synthetic test dataset generated by the platform.", processing_status="RAW_SYNTHETIC"))
            dataset_id = result.inserted_primary_key[0]

            for _, row in df.iterrows():
                station_result = conn.execute(stations.insert().values(dataset_id=dataset_id, station_id=row["Point_ID"], line_id=row["Line_ID"], survey_datetime=row["Date_Time"].to_pydatetime() if hasattr(row["Date_Time"], "to_pydatetime") else row["Date_Time"], latitude=float(row["Latitude"]), longitude=float(row["Longitude"]), elevation_m=float(row["Elevation_m"]), easting_m=float(row["Easting_km_local"]) * 1000.0, northing_m=float(row["Northing_km_local"]) * 1000.0, crs_epsg=4326, quality_flag=str(row["Quality_Flag"])))
                station_pk = station_result.inserted_primary_key[0]
                if "Mag_Raw_TMI_nT" in df.columns and pd.notna(row.get("Mag_Raw_TMI_nT")):
                    conn.execute(magnetic.insert().values(station_pk=station_pk, raw_tmi_nt=float(row["Mag_Raw_TMI_nT"]), base_station_nt=float(row["Mag_Base_Station_nT"]), diurnal_correction_nt=float(row["Mag_Diurnal_Correction_nT"]), igrf_reference_nt=float(row["Mag_IGRF_Reference_nT"]), heading_correction_nt=float(row.get("Mag_Heading_Correction_nT", 0.0)), lag_correction_nt=float(row.get("Lag_Correction_nT", 0.0)), leveling_correction_nt=float(row.get("Mag_Leveling_Correction_nT", 0.0)), microleveling_correction_nt=0.0, final_anomaly_nt=float(row["Mag_Anomaly_nT"])))
                if "Gravity_Raw_mGal" in df.columns and pd.notna(row.get("Gravity_Raw_mGal")):
                    conn.execute(gravity.insert().values(station_pk=station_pk, raw_gravity=float(row["Gravity_Raw_mGal"]), base_station_gravity=float(row["Gravity_Base_mGal"]), tide_correction_mgal=float(row["Gravity_Tide_Correction_mGal"]), drift_correction_mgal=float(row["Gravity_Drift_Correction_mGal"]), latitude_correction_mgal=float(row["Gravity_Latitude_Correction_mGal"]), free_air_correction_mgal=float(row["Gravity_Free_Air_Correction_mGal"]), bouguer_correction_mgal=float(row["Gravity_Bouguer_Correction_mGal"]), terrain_correction_mgal=float(row["Gravity_Terrain_Correction_mGal"]), curvature_correction_mgal=float(row["Gravity_Curvature_Correction_mGal"]), isostatic_correction_mgal=float(row["Gravity_Isostatic_Correction_mGal"]), final_anomaly_mgal=float(row["Gravity_Complete_Bouguer_mGal"])))
        return True, f"Saved {len(df):,} synthetic stations to external database in schema '{schema or 'default'}'."
    except Exception as exc:
        return False, f"Could not save synthetic dataset: {exc}"
    finally:
        engine.dispose()


def render_synthetic_data(user: dict):
    st.title("🧪 Synthetic Geophysical Data Laboratory")
    st.caption("Synthetic data are for demonstration, algorithm testing and software QA. They are not measured survey data.")

    template = st.selectbox("Survey / data template", list(SURVEY_TEMPLATES.keys()), key="syn_template")
    st.info(SURVEY_TEMPLATES[template]["description"])

    c1, c2, c3 = st.columns(3)
    with c1:
        n_points = st.number_input("Measurement points", min_value=20, max_value=10000, value=SURVEY_TEMPLATES[template]["default_points"], step=20, key="syn_points")
        area_km = st.number_input("Area size (km)", min_value=1.0, max_value=500.0, value=20.0, step=1.0, key="syn_area")
    with c2:
        line_count = st.number_input("Survey lines", min_value=1, max_value=500, value=30, step=1, key="syn_lines")
        seed = st.number_input("Random seed", min_value=0, max_value=999999, value=42, step=1, key="syn_seed")
    with c3:
        noise = st.slider("Noise (%)", 0.0, 30.0, 5.0, 0.5, key="syn_noise")
        missing_mag = st.slider("Missing magnetic (%)", 0.0, 100.0, 0.0, 1.0, key="syn_miss_mag")
        missing_grav = st.slider("Missing gravity (%)", 0.0, 100.0, 0.0, 1.0, key="syn_miss_grav")

    loc1, loc2 = st.columns(2)
    with loc1:
        center_lat = st.number_input("Center latitude", -89.0, 89.0, 30.0, 0.1, key="syn_lat")
    with loc2:
        center_lon = st.number_input("Center longitude", -179.0, 179.0, 31.0, 0.1, key="syn_lon")

    if st.button("🧪 Generate Synthetic Survey", type="primary", use_container_width=True):
        df = generate_synthetic_survey(template, int(n_points), area_km, int(line_count), center_lat, center_lon, int(seed), noise, missing_mag, missing_grav)
        st.session_state["synthetic_df"] = df
        st.success(f"Generated {len(df):,} measurement points.")

    df = st.session_state.get("synthetic_df")
    if df is None:
        return

    st.subheader("Synthetic dataset")
    st.dataframe(df.head(100), use_container_width=True, height=420)

    q1, q2, q3, q4 = st.columns(4)
    q1.metric("Points", f"{len(df):,}")
    q2.metric("Latitude range", f"{df['Latitude'].min():.3f} → {df['Latitude'].max():.3f}")
    q3.metric("Longitude range", f"{df['Longitude'].min():.3f} → {df['Longitude'].max():.3f}")
    q4.metric("Template", template)

    st.subheader("Download")
    d1, d2 = st.columns(2)
    d1.download_button("Download CSV", df.to_csv(index=False).encode("utf-8"), "synthetic_geophysical_survey.csv", "text/csv", use_container_width=True)
    d2.download_button("Download Excel", _excel_bytes(df), "synthetic_geophysical_survey.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use_container_width=True)

    st.subheader("Save to active external database")
    url, platform, label, schema = _active_external()
    if url:
        st.success(f"Active external database: {label or platform} | schema: {schema or 'default'}")
        project_key = st.text_input("External project key", "SYNTHETIC_DEMO", key="syn_project_key")
        project_name = st.text_input("External project name", "Synthetic Geophysical Demonstration", key="syn_project_name")
        if st.button("💾 Save Synthetic Dataset to External Database", use_container_width=True):
            ok, msg = save_synthetic_to_external_db(df, project_key.strip(), project_name.strip(), schema or None)
            (st.success if ok else st.error)(msg)
    else:
        st.info("Connect to an external database in Database Manager to store the generated stations. Downloads remain available without a database connection.")
